pages/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'pages'

urlpatterns = [
    path('', TemplateView.as_view(template_name='pages/home.html'), name='home')
]

simple_portfolio_full_stack_app/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import CustomLoginView

urlpatterns = [
    path('portfolio-admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('todos/', include('todos.urls')),
    path('', include('pages.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/auth/login', CustomLoginView.as_view()),
    path('api/v1/auth/', include('knox.urls')),
]

todos/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (
    TodoListView,
    TodoDetailView,
    TodoCreateView,
    TodoUpdateView,
    SubtaskCreateView,
    TodoDeleteView,
    TodoAPIModelViewSet
)

app_name = 'todos'

router = DefaultRouter()
router.register('v1', TodoAPIModelViewSet, basename='todo')

urlpatterns = [
    path('', TodoListView.as_view(), name='list'),
    path('<uuid:pk>/', TodoDetailView.as_view(), name='detail'),
    path('new-todo/', TodoCreateView.as_view(), name='new_todo'),
    path('<uuid:pk>/update-todo', TodoUpdateView.as_view(), name='update_todo'),
    path('<uuid:parent_pk>/new-subtask/', SubtaskCreateView.as_view(), name='new_subtask'),
    path('<uuid:pk>/delete-todo/', TodoDeleteView.as_view(), name='delete_todo'),
    path('api/', include(router.urls)),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

todos/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from uuid import uuid4

user_model = get_user_model()


class Todo(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid4)
    text = models.TextField()
    complete = models.BooleanField(default=False)
    user = models.ForeignKey(user_model, on_delete=models.CASCADE)
    parent_task = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='subtasks'
    )
    created_timestamp = models.DateTimeField(auto_now_add=True)
    modified_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text if len(self.text) < 15 else self.text[:15] + '...'

    def get_absolute_url(self):
        return reverse('todos:detail', kwargs={'pk': self.pk})

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

todos/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import Todo


class TodoCreateModelForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-todo_create_form'
        self.helper.form_method = 'post'
        custom_submit = Submit('submit', 'Submit Todo')
        custom_submit.field_classes = 'btn btn-success'
        self.helper.add_input(custom_submit)


class TodoUpdateModelForm(TodoCreateModelForm):
    class Meta(TodoCreateModelForm.Meta):
        fields = ['text', 'complete']

accounts/views.py
from knox.views import LoginView
from rest_framework.authentication import BasicAuthentication


class CustomLoginView(LoginView):
    authentication_classes = [BasicAuthentication]

todos/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework.viewsets import ModelViewSet

from .forms import TodoCreateModelForm, TodoUpdateModelForm
from .models import Todo
from .serializers import TodoSerializer, NewTodoSerializer, UpdateTodoSerializer

class TodoListView(LoginRequiredMixin, generic.ListView):
    context_object_name = 'todos'

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user).filter(parent_task=None)


class TodoDetailView(LoginRequiredMixin, generic.DetailView):
    context_object_name = 'todo'

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user)


class TodoCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = TodoCreateModelForm
    template_name = 'todos/todo_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['text'].widget = forms.TextInput()
        return form


class TodoUpdateView(LoginRequiredMixin, generic.UpdateView):
    form_class = TodoUpdateModelForm
    template_name = 'todos/todo_form.html'
    context_object_name = 'todo'

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['text'].widget = forms.TextInput()
        return form


class SubtaskCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = TodoCreateModelForm
    template_name = 'todos/todo_form.html'

    def dispatch(self, request, *args, **kwargs):
        self.parent_task = get_object_or_404(
            Todo.objects.filter(user=self.request.user),
            pk=kwargs.get('parent_pk')
        )
        self.extra_context = {'parent_task': self.parent_task}
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.parent_task = self.parent_task
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['text'].widget = forms.TextInput()
        return form


class TodoDeleteView(LoginRequiredMixin, generic.DeleteView):
    success_url = reverse_lazy('todos:list')
    context_object_name = 'todo'

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user)


class TodoAPIModelViewSet(ModelViewSet):

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user).filter(parent_task=None)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def get_serializer_class(self):
        if self.request.method == 'GET':
            return TodoSerializer
        elif self.request.method == 'POST':
            return NewTodoSerializer
        else:
            return UpdateTodoSerializer

pages/templates/pages/home.html
{% extends "_base.html" %}

{% block title %}Home{% endblock %}

{% block base_nav %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'pages:home' %}">Home</a>
    </li>
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'todos:list' %}">Todo App</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="https://react-app.professionalcodingservices.com">React Todo App</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/todos/api/v1">Browsable API</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <h2>Welcome!</h2>
    <hr />
    <p>
        Thanks for visiting my simple portfolio website. This website is to show off some full-stack development skills
        that I have picked up so far. If you choose to sign up, you will have access to a simple todo application that I
        put together. I hope you enjoy seeing everything!
    </p>
    <p>
        This website was built with Django and is being hosted on Heroku. The RDBMS is Postgres.
    </p>
    <p>
        Great thanks to Will Vincent for putting out <em>Django for Professionals</em>, which was a major guide to the
        beginning of my development journey with Django. Here is a link to his
        <a href="https://wsvincent.com/">website</a>
        If you are looking for a guide to full-stack development with Django and Python, I definitely would recommend
        his Django books to start with.
    </p>
    <p>
        Major reason for requiring sign up: I don't plan on perusing users todos, and, therefore, to limit exposure of possible
        trolling profanity, segregating user interactions from others seemed like the best course of action.
    </p>
    <p>
        If you would like to use the todo app without signing up, which is totally reasonable, feel free to login with
        "anonymoususer@example.com" with the password "testpass123". The sign up workflow includes a verification email.
        So, mostly, the sign up is meant to segregate content and show my ability to generate emails through an API.
    </p>
    <p>
        Also, if you have signed up, you can also use the React SPA that interfaces with this same website. It is not as
        feature complete as this website, but I built it to demonstrate my ability to build an API, and interface an external frontend
        with said API.
    </p>
    <p>
        All the Best! — David V.
    </p>

{% endblock %}

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
            crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url "pages:home" %}">DV</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% block base_nav %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'todos:list' %}">Todo App</a>
                            </li>
                        {% endif %}
                    {% endblock %}
                    {% block extra_nav %}
                    {% endblock %}
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% block user_auth_nav %}
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                            </li>
                        {% endif %}
                    {% endblock %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

todos/templates/todos/todo_confirm_delete.html
{% extends '_base.html' %}

{% load crispy_forms_filters %}

{% block title %}Confirm Delete of Todo{% endblock %}

{% block extra_nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'todos:detail' pk=todo.pk %}">Back to Todo</a>
    </li>
{% endblock %}

{% block content %}
    <h2>Confirm Delete</h2>
    <p>Todo to Delete: {{ todo }}</p>
    <hr />
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-danger">Confirm Delete</button>
    </form>
{% endblock %}

todos/templates/todos/todo_detail.html
{% extends '_base.html' %}

{% block base_nav %}
    <li class="nav-item">
        <a href="{% url 'pages:home' %}" class="nav-link">Home</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'todos:list' %}" class="nav-link active">Todo App</a>
    </li>
{% endblock %}

{% block extra_nav %}
    <li class="nav-item">
        <a href="{% url 'todos:new_todo' %}" class="nav-link">New Todo</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'todos:update_todo' pk=todo.pk %}" class="nav-link">Update Todo</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'todos:new_subtask' parent_pk=todo.pk %}" class="nav-link">New Subtask</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'todos:delete_todo' pk=todo.pk %}" class="nav-link">Delete Todo</a>
    </li>
{% endblock %}

{% block content %}
    <h2>Todo Detail</h2>
    {% if todo.parent_task %}
        <hr />
        <p>Parent Todo: <a href="{% url "todos:detail" pk=todo.parent_task.pk %}">{{ todo.parent_task }}</a></p>
        <p>Parent Status: {{ todo.parent_task.complete|yesno:"Complete, Not Complete" }}</p>
    {% endif %}
    <hr />
    <p>Todo: {{ todo.text }}</p>
    <p>Status: {{ todo.complete|yesno:"Is Complete, Not Complete" }}</p>
    <p>Created: {{ todo.created_timestamp }}</p>
    <p>Last Modified: {{ todo.modified_timestamp }}</p>
    {% if todo.subtasks.all %}
        <hr />
        <h4>Subtasks</h4>
    {% endif %}
    {% for subtask in todo.subtasks.all %}
        <p><a href="{% url "todos:detail" pk=subtask.pk %}">{{ subtask }}</a>: {{ subtask.complete|yesno:"Complete, Not Complete" }}</p>
    {% endfor %}
{% endblock %}

todos/templates/todos/todo_form.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% crispy form form.helper %}

{% block title %}New Todo{% endblock %}

{% block extra_nav %}
    {% if 'update' in request.path %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'todos:detail' pk=todo.pk %}">Back to Todo</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'todos:update_todo' pk=todo.pk %}">Update Todo</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'todos:new_todo' %}">New Todo</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    {% if 'update' in request.path %}
        <h2>Update Todo</h2>
    {% else %}
        <h2>New Todo</h2>
    {% endif %}
    <hr />
    {% crispy form %}
{% endblock %}

todos/templates/todos/todo_list.html
{% extends '_base.html' %}

{% block base_nav %}
    <li class="nav-item">
        <a href="{% url 'pages:home' %}" class="nav-link">Home</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'todos:list' %}" class="nav-link active">Todo App</a>
    </li>
{% endblock %}

{% block extra_nav %}
    <li class="nav-item">
        <a href="{% url 'todos:new_todo' %}" class="nav-link">New Todo</a>
    </li>
{% endblock %}

{% block content %}
    <h2>Todo List</h2>
    <hr />
    {% for todo in todos %}
        <p><a href="{% url 'todos:detail' pk=todo.pk %}">{{ todo }}</a></p>
    {% endfor %}
{% endblock %}